js_compiler:

  uglifyjs src/scrollable.fullwidth.js --comments all \
	   -o scripts/scrollable.fullwidth.min.js
	
  cat scripts/scrollable.min.js \
      scripts/scrollable.autoscroll.min.js \
      scripts/scrollable.navigator.min.js \
      scripts/scrollable.fullwidth.min.js \
    > scripts/scrollable.all.min.js

